# Generated by Django 4.1 on 2022-09-14 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_profile_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allocated', models.BooleanField(default=False)),
                ('title', models.TextField(max_length=500)),
                ('description', models.TextField()),
                ('in_scope', models.TextField()),
                ('out_scope', models.TextField()),
                ('skill', models.TextField()),
                ('team_size', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('sponsor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
