# Generated by Django 4.1 on 2022-09-22 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allocated', models.BooleanField(default=False)),
                ('title', models.TextField(default=' ', max_length=500)),
                ('description', models.TextField(default=' ')),
                ('in_scope', models.TextField(default=' ')),
                ('out_scope', models.TextField(default=' ')),
                ('skill', models.TextField(default=' ')),
                ('team_size', models.IntegerField(default=4)),
                ('duration', models.IntegerField(default=12)),
                ('sponsor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
