# Generated by Django 4.1 on 2022-09-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='project',
            name='in_scope',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='project',
            name='out_scope',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='project',
            name='skill',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_size',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(default=' ', max_length=500),
        ),
    ]
