# Generated by Django 4.1 on 2022-10-10 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_profile_choice1_remove_profile_choice2_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='member', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sponsor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_id', to='accounts.profile'),
        ),
    ]
