# Generated by Django 4.1 on 2022-10-10 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_profile_choice1_remove_profile_choice2_and_more'),
        ('projects', '0002_project_member_alter_project_sponsor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='member',
        ),
        migrations.AddField(
            model_name='project',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocated_group', to='accounts.group'),
        ),
    ]
