# Generated by Django 4.1 on 2022-10-23 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_group_choice1_alter_group_choice2_and_more'),
        ('projects', '0005_alter_project_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_group', to='accounts.group'),
        ),
    ]
