# Generated by Django 4.1 on 2022-09-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='identity',
            field=models.IntegerField(choices=[(1, 'Convener'), (2, 'Sponsor'), (3, 'Student')], default=3),
        ),
    ]
