# Generated by Django 4.1 on 2022-09-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unit_code',
            field=models.IntegerField(blank=True, choices=[], default=0),
        ),
    ]
