# Generated by Django 4.1 on 2022-09-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='project_id',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
