# Generated by Django 4.1 on 2022-09-22 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='project_id',
        ),
    ]
