# Generated by Django 4.1 on 2022-09-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_choice1_remove_profile_choice2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
