# Generated by Django 4.1 on 2022-10-10 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('accounts', '0009_group_choice2_group_choice3_alter_group_choice1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='choice1',
            field=models.ForeignKey(default='Dummy', on_delete=django.db.models.deletion.CASCADE, related_name='choice1', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='group',
            name='choice2',
            field=models.ForeignKey(default='Dummy', on_delete=django.db.models.deletion.CASCADE, related_name='choice2', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='group',
            name='choice3',
            field=models.ForeignKey(default='Dummy', on_delete=django.db.models.deletion.CASCADE, related_name='choice3', to='projects.project'),
        ),
    ]
