# Generated by Django 4.1 on 2022-10-10 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_group_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='choice3',
        ),
    ]
