# Generated by Django 4.1 on 2022-10-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_profile_unit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_allocated',
            field=models.BooleanField(default=False),
        ),
    ]
