# Generated by Django 4.1 on 2022-10-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_group_is_allocated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unit_code',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (9785, '9785'), (9786, '9786'), (10004, '10004'), (10005, '10005'), (10098, '10098'), (11522, '11522')], default=0),
        ),
    ]
