# Generated by Django 4.1 on 2022-10-23 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_member'),
        ('accounts', '0019_alter_group_choice1_alter_group_choice2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='choice1',
            field=models.ForeignKey(blank=True, default='2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice1', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='group',
            name='choice2',
            field=models.ForeignKey(blank=True, default='2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice2', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='group',
            name='choice3',
            field=models.ForeignKey(blank=True, default='2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice3', to='projects.project'),
        ),
    ]
